import { useParams, useNavigate } from '@tanstack/react-router'
import { useInsight, useRefreshInsight } from '@features/insights'
import { InsightCard } from '@features/insights'
import { Button, Spinner } from "@elimu-sight/ui"
import { useQueryClient } from '@tanstack/react-query'
import { formatDate } from '@shared/lib/formatters'
import { Badge } from "@elimu-sight/ui"

export function InsightDetailPage() {
  const navigate = useNavigate()
  const queryClient = useQueryClient()
  const { insightId } = useParams({ from: '/dashboard/insights/$insightId' })
  const { data: insight, isLoading } = useInsight(insightId)
  const refreshInsight = useRefreshInsight()

  if (isLoading) {
    return (
      <div className="flex justify-center py-12">
        <Spinner />
      </div>
    )
  }

  if (!insight) {
    return (
      <div className="space-y-6">
        <h1 className="text-2xl font-bold text-gray-900">Insight not found</h1>
        <Button onClick={() => navigate({ to: '/dashboard/insights' })}>Back to Insights</Button>
      </div>
    )
  }

  const handleRefresh = () => {
    refreshInsight.mutate(insightId, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: ['insights', insightId] })
      },
    })
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <button
            onClick={() => navigate({ to: '/dashboard/insights' })}
            className="text-sm text-blue-600 hover:text-blue-500"
          >
            &larr; Back to Insights
          </button>
          <h1 className="mt-1 text-2xl font-bold text-gray-900">{insight.title || 'Untitled Insight'}</h1>
        </div>
        <Button onClick={handleRefresh} disabled={refreshInsight.isPending}>
          {refreshInsight.isPending ? 'Refreshing...' : 'Refresh Insight'}
        </Button>
      </div>

      <div className="rounded-xl border bg-white p-6">
        <div className="flex items-start justify-between">
          <div className="space-y-4">
            {insight.type && <Badge>{insight.type}</Badge>}
            {insight.summary && (
              <p className="text-gray-700">{insight.summary}</p>
            )}
            {insight.data && (
              <div className="rounded-lg bg-gray-50 p-4">
                <pre className="text-sm text-gray-600 whitespace-pre-wrap">
                  {typeof insight.data === 'string' ? insight.data : JSON.stringify(insight.data, null, 2)}
                </pre>
              </div>
            )}
          </div>
          <div className="flex flex-col items-end gap-2 text-sm text-gray-500">
            {insight.confidenceScore !== undefined && (
              <span>{Math.round(insight.confidenceScore)}% confidence</span>
            )}
            {insight.generatedBy && <span>Generated by: {insight.generatedBy}</span>}
            {insight.period && <span>Period: {insight.period}</span>}
            <span>{formatDate(insight.createdAt)}</span>
          </div>
        </div>
      </div>
    </div>
  )
}
