export {AuthController} from "./auth.controller";
export {SchoolController} from "./school.controller";
export {UserController} from "./user.controller"
export {ClassController} from "./class.controller";
export {SubjectController} from "./subject.controller";
export {ClassSubjectController} from "./class-subject.controller";
export {StudentController} from "./student.controller";
export {AssessmentController} from "./assessment.controller";
export {InsightController} from "./insight.controller";
export {AIController} from "./ai.controller";
export {DashboardController} from "./dashboard.controller";
export {AdminController} from "./admin.controller";
