export const ROUTES = {
  HOME: '/',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  DASHBOARD: '/dashboard',
  USERS: '/dashboard/users',
  ANALYTICS: '/dashboard/analytics',
  SETTINGS: '/dashboard/settings',
  STUDENTS: '/dashboard/students',
  STUDENT_DETAIL: (id: string) => `/dashboard/students/${id}`,
  ASSESSMENTS: '/dashboard/assessments',
  ASSESSMENT_CREATE: '/dashboard/assessments/new',
  ASSESSMENT_DETAIL: (id: string) => `/dashboard/assessments/${id}`,
  INSIGHTS: '/dashboard/insights',
  INSIGHT_DETAIL: (id: string) => `/dashboard/insights/${id}`,
  CLASSES: '/dashboard/classes',
  CLASS_DETAIL: (id: string) => `/dashboard/classes/${id}`,
  SUBJECTS: '/dashboard/subjects',
  TEACHERS: '/dashboard/teachers',
  TEACHER_DETAIL: (id: string) => `/dashboard/teachers/${id}`,
  SCHOOLS: '/dashboard/schools',
  SCHOOL_DETAIL: (id: string) => `/dashboard/schools/${id}`,
  ADMIN: '/dashboard/admin',
  ADMIN_TENANTS: '/dashboard/admin/tenants',
  ADMIN_TENANT_DETAIL: (id: string) => `/dashboard/admin/tenants/${id}`,
  ADMIN_USERS: '/dashboard/admin/users',
  ADMIN_AI: '/dashboard/admin/ai',
  ADMIN_HEALTH: '/dashboard/admin/health',
  ADMIN_SECURITY: '/dashboard/admin/security',
  ADMIN_BILLING: '/dashboard/admin/billing',
  ADMIN_ANNOUNCEMENTS: '/dashboard/admin/announcements',
  ADMIN_SUPPORT: '/dashboard/admin/support',
  MY_CLASS: '/dashboard/my-class',
} as const
