export const ROUTES = {
  HOME: '/',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  DASHBOARD: '/dashboard',
  ANALYTICS: '/dashboard/analytics',
  SETTINGS: '/dashboard/settings',
  STUDENTS: '/dashboard/students',
  STUDENT_DETAIL: (id: string) => `/dashboard/students/${id}`,
  ASSESSMENTS: '/dashboard/assessments',
  ASSESSMENT_CREATE: '/dashboard/assessments/new',
  ASSESSMENT_DETAIL: (id: string) => `/dashboard/assessments/${id}`,
  INSIGHTS: '/dashboard/insights',
  INSIGHT_DETAIL: (id: string) => `/dashboard/insights/${id}`,
  CLASSES: '/dashboard/classes',
  CLASS_DETAIL: (id: string) => `/dashboard/classes/${id}`,
  SUBJECTS: '/dashboard/subjects',
  TEACHERS: '/dashboard/teachers',
  SCHOOLS: '/dashboard/schools',
  SCHOOL_DETAIL: (id: string) => `/dashboard/schools/${id}`,
} as const
