export { analyticsClient } from './api/analytics-client'
export { usePerformanceAnalytics } from './hooks/use-performance-analytics'
export { useRiskAnalysis } from './hooks/use-risk-analysis'
export { useTrends } from './hooks/use-trends'
export { PerformanceChart } from './components/performance-chart'
export { TrendChart } from './components/trend-chart'
export { SummaryStats } from './components/summary-stats'
export { RiskMatrix } from './components/risk-matrix'
