export { teacherClient } from './api/teacher-client'
export { useTeachers } from './hooks/use-teachers'
export { useTeacher } from './hooks/use-teacher'
export { useCreateTeacher } from './hooks/use-create-teacher'
export { useUpdateTeacher } from './hooks/use-update-teacher'
export { useAssignClass } from './hooks/use-assign-class'
export { TeacherTable } from './components/teacher-table'
export { TeacherCard } from './components/teacher-card'
export { TeacherDetailCard } from './components/teacher-detail-card'
export { TeacherAssignClass } from './components/teacher-assign-class'
export { teacherSchema, updateTeacherSchema, assignClassSchema } from './schemas/teacher-schema'
export type { TeacherFormData, TeacherUpdateInput, ClassAssignment } from './types'
