export { adminClient } from './api/admin-client'
export {
  useAdminOverview,
  useSystemHealth,
  useAdminSchools,
  useAdminSchoolDetail,
  useAdminUsers,
  useAIUsage,
  useAIUsageTrends,
  useInsightStats,
  useAuditLogs,
  useAuditLogStats,
  useSecurityOverview,
  useBillingOverview,
  useAnnouncements,
  useSupportTickets,
  useCreateSchool,
  useUpdateSchool,
  useDeleteSchool,
  useCreateUser,
  useUpdateUser,
  useDeactivateUser,
  useChangeSchoolPlan,
  useCreateAnnouncement,
  useUpdateAnnouncement,
  useDeleteAnnouncement,
  useUpdateSupportTicket,
} from './hooks/use-admin'
